name: Continuous Integration and Deployment for Data Collector

on:
  push:
    branches:
      - main
    paths:
      - 'data-collector/functions/**'

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .runtimeconfig.json
        run: |
          echo '{
            "newsapi": {
              "apikey": "${{ secrets.NEWS_API_KEY }}"
            }
          }' > ./data-collector/functions/.runtimeconfig.json

      - name: Install dependencies
        run: npm install
        working-directory: ./data-collector/functions

      - name: Build the project
        run: npm run build
        working-directory: ./data-collector/functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Start Firestore Emulator
        run: |
          firebase emulators:start --only firestore --project newssentimentanalyzer &
        working-directory: ./data-collector/functions

      - name: Wait for Firestore Emulator to start
        run: sleep 15

      - name: Run tests
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
        run: npm run test
        working-directory: ./data-collector/functions

      - name: Deploy to Firebase
        if: success()
        run: firebase deploy --only functions:scheduledNewsCollection,functions:requestNewsCollection --project newssentimentanalyzer --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
        working-directory: ./data-collector/functions
